version: "3.8"

services:
  build:
    image: jruby
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    # command: jruby -S bundler install 
    command: gem build logstash-filter-sizing.gemspec

  example:
    build: .
    container_name: sizing
    volumes:
      - ./example/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./example/config:/usr/share/logstash/conf/